#!/bin/bash

sed -e's/^#?PasswordAuthentication.*/PasswordAuthentication no/g' -i /etc/ssh/sshd_config
sed -e's/^#?ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/g' -i /etc/ssh/sshd_config
sed -e's/^#?PermitRootLogin.*/PermitRootLogin no/g' -i /etc/ssh/sshd_config

rm -f /etc/ssh/ssh_host_*
test -f /etc/ssh/ssh_host_dsa_key || dpkg-reconfigure openssh-server
