#!/bin/bash

PROGNAME=$(basename $(readlink -f $0))
systemctl stop systemd-timesyncd
date --set="$(stat /lost+found |grep Change |sed -e 's/^Change: //g' -e 's/+0000//g')"
systemctl start systemd-timesyncd
